title: Using remote pins on a Raspberry Pi
hero_image: images/banner.png
description: Access the pins on a remote Raspberry Pi
original_url:
theme: red 
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: 
interests:
technologies: "physical computing"
steps:
  - title: Using remote pins
