title: rpi-python-remote-pins
hero_image: images/banner.png
description: rpi-python-remote-pins description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: red # all possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games, jokes/pranks, music/sound, photography, physical computing, robots, space"
technologies: "electronics, html/css, physical computing, python, scratch"
steps:
  - title: Step one
